n = (input('Digite um valor e eu falarei sobre ele: '))
print('Seu valor é um número?',n.isnumeric())
print('Seu valor é alpha númerico?',n.isalnum())
print('Seu valor são letras?',n.isalpha())
print('Seu valor é um digito?',n.isdigit())
print('Seu valor é um número decimal?',n.isdecimal())
print('Seu valor pode ser usado para nome de variavel?',n.isidentifier())
print('Seu valor está minúsculo?',n.islower())
print('Seu valor é imprimivel?',n.isprintable())
print('Seu valor é um espaço em branco?',n.isspace())
print('Seu valor começa com letra maiúscula?',n.istitle())
print('Seu valor é maiúsculo?',n.isupper())
